[package]
name = "minae-chess"
version = "0.1.0"
authors = ["Adam Britton <adj.britton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"